### ISSUE TITLE
Docker compose for ATTX sandbox

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/platform-deployment#1]
DoD:

Create docker-compose stack for ATTX solution
* Workflow component
* Graph Manager component
* public APIs
* messaging (if needed)

Testing:
BDD integration test

**Comment by joasilva** [comment]
BDD Tests: https://github.com/ATTX-project/platform-deployment/commit/b1bd95293b10d3b07eb2a88bb15248760d774716
