### ISSUE TITLE
Add GMApi to the docker compose 

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#10]
#### Description
GMAPi is a new component that needs to added to the platform stack.
#### DoD
Docker-compose up also starts the gmAPI
#### Testing
peer-review

**Comment by blankdots** [comment]
GM API needs to bind with:
* Fuseki
* Elasticsearch 5.1.2
* Workflow API

**Comment by joasilva** [comment]
Updated build-gradle here: https://github.com/ATTX-project/platform-deployment/blob/dev/build.gradle
