### ISSUE TITLE
Run tests within a container 

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#14]
#### Description
Figure out a way to run tests in a container created with gradle plugin and run by Jenkins.
Actual test can be something really simple like "print 'hello world'"
#### DoD
Jenkins pipeline that runs the tests and outputs reports

#### Testing
Peer-review

**Comment by jkesanie** [comment]
You can test this with the graph-component/gc-feature-tests

https://github.com/ATTX-project/project-management/wiki/Containerized-testing

**Comment by blankdots** [comment]
from an older issue: http://blog.terranillius.com/post/docker_testing/
