### ISSUE TITLE
Report on CSC's services for running ATTX components

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#18]
#### Description
Figure out how to access CSC's cloud services for running out component images. 
Report on different ways to utilize CSC's services.

#### DoD
Report
- describe testing scenarios (i.e. what did we try to do)
  - configurations
  - test datasets
- customer services
- documentation
- tools/services available, **including APIs**
- pricing

#### Testing
Peer-review.

**Comment by joasilva** [comment]
Report ready for review at https://github.com/ATTX-project/project-management/wiki/CSC-cPouta-Cloud-Services-Report.

**Comment by blankdots** [comment]
Maybe as part of the documentation we can also include their training website https://www.csc.fi/web/training (e.g. https://www.csc.fi/web/training/-/webinar-virtual-machine-ansible-2017)
