### ISSUE TITLE
Create Docker-compose for ATTX dev

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/platform-deployment#2]
DoD:

Create docker-compose or dev environment:
* CI e.g. Jenkins
* CD e.g. Docker Private Registry
* push new container should be pushed to Docker Hub
* Test configuration

Testing:
Peer review

**Comment by joasilva** [comment]
The docker-compose stack should launch attx-jenkins with the following options:

`/usr/bin/docker run --link picy_repo:pivyrepo -d -v /var/run/docker.sock:/var/run/docker.sock -v $(which docker):/usr/bin/docker -p 49001:8080 -v /data/jenkins:/var/jenkins_home -t attxproject/attx-jenkins:latest`
