### ISSUE TITLE
Generate release artifacts

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#21]
#### Description
Release consists of three type of artifacts:
- source code
- packaged applications
- images

We have to come up with a way to generate, tag and publish these different artifact types for every release. 

#### DoD
Working process for creating different types of artifacts for a release. That is, when we want to make a release version X, there are definition and implementation of steps that should be executed to make it happen.

#### Testing

Peer-review

**Comment by blankdots** [comment]
https://github.com/ATTX-project/project-management/wiki/Build-Multiple-Environments
