### ISSUE TITLE
Hot deployment of new image versions to running stack

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#22]
#### Description

We want to update specific container running on a server. 
- startup new version
- do something
- stop old version

To be also done: Images on the docker hub and on the private registry should have the same name and different tags for test/dev/prod (the tags can be handled in a different issues however the names need to be consistent).

#### DoD

Implement the 'do something' part. 
Script or similar to update component X to version Y. 

#### Testing
Peer-review

**Comment by joasilva** [comment]
It works as such (tested with Redis):
Create a test service:
madeira@lx6-hulib-2:~/workspace/ATTX-project/ATTX-project.github.io/Import/attx_project$ docker service create \
>   --replicas 3 \
>   --name redis \
>   --update-delay 10s \
>   redis:3.0.6
abzmumhsytqr52ubxdp4gi6gq

Check the new service status:
madeira@lx6-hulib-2:~/workspace/ATTX-project/ATTX-project.github.io/Import/attx_project$ docker service inspect --pretty redis

ID:		abzmumhsytqr52ubxdp4gi6gq
Name:		redis
Service Mode:	Replicated
 Replicas:	3
Placement:
UpdateConfig:
 Parallelism:	1
 Delay:		10s
 On failure:	pause
 Max failure ratio: 0
ContainerSpec:
 Image:		redis:3.0.6@sha256:6a692a76c2081888b589e26e6ec835743119fe453d67ecf03df7de5b73d69842
Resources:
Endpoint Mode:	vip

Check Swarm services status:
madeira@lx6-hulib-2:~/workspace/ATTX-project/ATTX-project.github.io/Import/attx_project$ docker service ls
ID            NAME        MODE        REPLICAS  IMAGE
7c8cwirfywq3  util        global      3/3       alpine:latest
abzmumhsytqr  redis       replicated  0/3       redis:3.0.6
ake5t0m88xpt  go-demo-db  replicated  1/1       mongo:3.2.10
p9rhg18ya6vx  proxy       replicated  6/6       vfarcic/docker-flow-proxy:latest
sqxup0tzavz1  my_web      replicated  1/1       nginx:latest
w4ra2t1tr75q  go-demo     replicated  1/1       vfarcic/go-demo:1.0

APPLY ROLLING UPDATE:
madeira@lx6-hulib-2:~/workspace/ATTX-project/ATTX-project.github.io/Import/attx_project$ docker service update --image redis:3.0.7 redis

redis

Check the service status:
madeira@lx6-hulib-2:~/workspace/ATTX-project/ATTX-project.github.io/Import/attx_project$ docker service inspect --pretty redis

ID:		abzmumhsytqr52ubxdp4gi6gq
Name:		redis
Service Mode:	Replicated
 Replicas:	3
UpdateStatus:
 State:		updating
 Started:	22 seconds
 Message:	update in progress
Placement:
UpdateConfig:
 Parallelism:	1
 Delay:		10s
 On failure:	pause
 Max failure ratio: 0
ContainerSpec:
 Image:		redis:3.0.7@sha256:b562e3febd22fe3b0db9df909c251910ae4f1a962339e52b3d69e72f3121bd64
Resources:
Endpoint Mode:	vip

Check Docker Swarm status:
madeira@lx6-hulib-2:~/workspace/ATTX-project/ATTX-project.github.io/Import/attx_project$ docker service ps redis
ID            NAME         IMAGE        NODE     DESIRED STATE  CURRENT STATE                ERROR  PORTS
umu55ho03f0p  redis.1      redis:3.0.7  swarm-2  Running        Running about a minute ago          
40n5oyip7lmh   \_ redis.1  redis:3.0.6  swarm-2  Shutdown       Shutdown about a minute ago         
u9kbpoeo0frr  redis.2      redis:3.0.7  swarm-1  Running        Running about a minute ago          
zhrethvjzuv3   \_ redis.2  redis:3.0.6  swarm-1  Shutdown       Shutdown about a minute ago         
s3aa0rr3kqvm  redis.3      redis:3.0.7  swarm-3  Running        Running 30 seconds ago              
og0sjazv3jgy   \_ redis.3  redis:3.0.6  swarm-3  Shutdown       Shutdown 50 seconds ago

**Comment by joasilva** [comment]
Ready for review, new document pushed to https://github.com/ATTX-project/ATTX-project.github.io/blob/dev/Import/attx_project/Applying-Rolling-Updates-to-services-in-Docker-Swarm.md

**Comment by jkesanie** [comment]
Documentation seems ok, but I did not have the time to test it myself.
