### ISSUE TITLE
Get rid of dpu jars in the pd-feature-tests project

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#23]
#### Description
Instead of having dummy jar files as part of the pd-feature-tests project, download all the required plugins from the artifact repository when they are needed.
Depends on https://github.com/ATTX-project/project-management/issues/81
#### DoD
Jars removed. 
Tests updated so that they use archiva.

#### Testing
Peer-review

**Comment by blankdots** [comment]
Removed metadata DPU (the only one currently available there).
The integration tests need to be run with new command:
`gradle -PregistryURL=attx-dev:5000 -PartifactRepoURL=http://attx-dev:8081 integTest`
