### ISSUE TITLE
DevOps: Implementing Pull Requests with Jenkins

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#24]
#### Description

Adding tests to the pull requests, and releases with pull requests for each repository/artifact.

#### DoD
Test the pull requests workflow from Jenkins to Github, based on tests.
#### Testing
Peer review

**Comment by blankdots** [comment]
@jkesanie and @joasilva although the connection is now available to github it seems it did not do the trick. The recommended set of actions are in "jenkink's wors":

> If your Jenkins runs inside the firewall and not directly reachable from the internet, set up a reverse proxy, port tunneling, and so on so that GitHub can deliver a POST request to your Jenkins at http://attx-dev:49001/github-webhook/. Then specify the URL that GitHub should POST to here.

**Comment by blankdots** [comment]
see provenance-service pipeline for the configuration
Also the service account needs to be set up in the repository for the github-webook to work
This means we do not need to set up the Jenkinsfile in each repository as Gradle can be configured in the pipeline.
