### ISSUE TITLE
Automatic publishing of release images to Dockerhub

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/platform-deployment#25]
#### Description
Publish images to DockerHub so that other people can download them.
Publishing should be trigger by *something* and only once.
Implementation might require new Jenkins pipelines.
See release plan for guidance.

#### DoD
Way of making version tagged release of images to DockerHub.
#### Testing
Peer Review

**Comment by blankdots** [comment]
One possible (tested) solution could be:
```{groovy}
plugins {
    id "com.chrisgahlert.gradle-dcompose-plugin" version "0.9.0"
}

apply plugin: 'com.chrisgahlert.gradle-dcompose-plugin'
apply plugin: 'base'

repositories {
      mavenCentral();
}

ext {
    imageRepo = "attx-dev"
    imageRepoPort = "5000"
}

if (!project.hasProperty("env") || project.env == "dev") {
    ext.imageFuseki = "dockerTest"
    ext.imageBase   = "${imageRepo}:${imageRepoPort}/attx-fuseki:${imageFuseki}"

} else if (project.env == "release"){
    ext.imageFuseki = "dockerTest2"
    ext.imageBase   = "attxtest/attx-fuseki:${imageFuseki}"

    if (!project.hasProperty("dockerUser") || !project.hasProperty("dockerPass")) {
        throw new GradleException("No Username and Password combo for DockerHub.")
    } else {
        ext.dockerUser = project.dockerUser
        ext.dockerPass = project.dockerPass
    }
    dcompose {
        dockerClientConfig = {
            withRegistryUsername "$dockerUser"
            withRegistryPassword "$dockerPass"
        }
    }
} else {
    throw new GradleException("Build project environment option not recognised.")
}

if (!project.hasProperty("registryURL")) {
    ext.registryURL = "http://${imageRepo}:${imageRepoPort}"
}

dcompose {
    registry ("$registryURL") {
        // Needs no user/pass
    }

    attxfuseki {
        baseDir = file('.')
	    dockerFilename = 'Dockerfile'
	    repository = imageBase
        attachStdout = true
        exposedPorts = ['3030']
        portBindings = ['3030:3030']
    }
}
```

The commands for this would require having a service account and the password exposed:
`gradle -PregistryURL=attx-dev:5000 -Penv=release -PdockerUser=account -PdockerPass=test123 pushAttxfusekiImage` - pushing to public docker hub

`gradle -PregistryURL=attx-dev:5000 pushAttxfusekiImage` - pushing to private registry

Another solution would involve using: https://github.com/bmuschko/gradle-docker-plugin and the example reflected in the tests: https://github.com/bmuschko/gradle-docker-plugin/blob/v0.8/src/integTest/groovy/com/bmuschko/gradle/docker/DockerWorkflowIntegrationTest.groovy#L160

**Comment by blankdots** [comment]
Towards a proposal as to what could trigger the deployment of the images to public - it would be successful pd-feature-tests.

**Comment by jkesanie** [comment]
+1 to pd-feature-tests. Could we concentrate all of our integration tests in that one project? Pros and cons?

**Comment by blankdots** [comment]
@jkesanie We can, some arguments I can think of:
* the Pros are that:
   * we will have one set of integration tests that will test integration between all components;
   * easier to maintain.
* the cons are that:
  * it take most likely longer;
  * if we want to test just a small part we will not be able to, unless we can make the tests allow that;
  * it will be more like end to end testing, and we have in PD BDD in the others we have Integration tests - meaning the scope and design of the tests are different.

Done so far:
* Current test images available in: https://hub.docker.com/u/attxtest/
* A new gradle plugin was added in the file `publishDocker.gradle` and imported using `apply from: '../publishDocker.gradle'` in each subproject
* To illustrate the changes that need to be made to the private repository image pipelines, GM API image pipeline was build: `gm-api-image-test`
* To illustrate the changes that need to be made to the feature tests pipelines, PD Feature Tests pipeline was build: `pd-feature-tests-try`

To publish image for **dev** one can use the following command:
`gradle -PregistryURL=attx-dev:5000 -PartifactRepoURL=http://attx-dev:8081 -Penv=dev pushWfapiImage`

To publish image for **release** one can use the following command:
`gradle -PregistryURL=attx-dev:5000 -PartifactRepoURL=http://attx-dev:8081 -Penv=release -PdockerUser=account -PdockerPass=test123 pushWfapiImage`

To run the tests a new parameter is needed `-Penv` e.g:
`gradle -PregistryURL=attx-dev:5000 -PartifactRepoURL=http://attx-dev:8081 -Penv=dev -PtestEnv=CI clean runContainerTests`

**Comment by jkesanie** [comment]
Putting this back to in progress, because we need new release pipelines (+ docker hub service account).
