### ISSUE TITLE
Provisioning of ATTX components on OpenStack

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#26]
#### Description
Documentation and files related to provisioning ATTX nodes on a OpenStack cloud.
#### DoD
Documentation can be used to replicate provisioning.
#### Testing
Peer review

**Comment by joasilva** [comment]
Documentation available @https://github.com/ATTX-project/project-management/wiki/Provisioning-ATTX-Components-on-CSC-Open-Stack-(cPouta)

**Comment by joasilva** [comment]
Ansible files pushed here: https://github.com/ATTX-project/platform-deployment/tree/feature-swarm-mode/swarm-mode-cpouta
