### ISSUE TITLE
Modify images so they do not run with privileged user

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/platform-deployment#27]
#### Description
Current Docker images need some user associated to running the service or the service should run under a supervisor e.g. http://supervisord.org/

Useful read: https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#user
maybe using https://github.com/tianon/gosu or https://github.com/ncopa/su-exec for alpine
#### DoD
Implement a supervisord configuration for containers or approriate solution
#### Testing
Peer review

**Comment by blankdots** [comment]
Useful read: https://denibertovic.com/posts/handling-permissions-with-docker-volumes/

**Comment by blankdots** [comment]
Identified images:

- [x] attx-gmapi
- [x] attx-wfapi
- [x] attx-pypirepo
- [x] attx-fuseki
- [x] attx-es5 (already had gosu set up, however I updated version to 1.10)
- [x] attx-essiren
- [ ] attx-jenkins - TBD

**Comment by blankdots** [comment]
There seems to be an issue with the ATTX es1.3.4 plugin in terms of packaging, Might be related to https://github.com/ATTX-project/project-management/issues/86 ?
```
[2017-03-21 07:17:39,814][WARN ][plugins                  ] [Mauvais] failed to load plugin from [file:/usr/share/elasticsearch/plugins/attx-es-api/es-plugin.properties]
org.elasticsearch.ElasticsearchException: Failed to load plugin class [org.hu.attx.apis.es.plugin.siren.ATTXApiPlugin]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:531)
	at org.elasticsearch.plugins.PluginsService.loadPluginsFromClasspath(PluginsService.java:406)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:115)
	at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:146)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:70)
	at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:203)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
Caused by: java.lang.ClassNotFoundException: org.hu.attx.apis.es.plugin.siren.ATTXApiPlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:508)
	... 7 more
```

**Comment by jkesanie** [comment]
It is related to the refactoring. Please change the package in the es-plugin.properties

**Comment by blankdots** [comment]
@joasilva and/or @jkesanie please review this issue, and if there are simpler or more efficient ways to do these, that I am missing we can adopt them.

------------------------
What was done:
I used `supervisord` to start services for some of the images such as: attx-gmapi, attx-wfapi, attx-pypirepo (probably an overkill for attx-gmapi and attx-wfapi - however after some documentation I think it is the right approach). Supervisord was started with limited privileges in all cases.
Fixed permissions for es5 - as there was a small permissions denied with the config folder for elasticsearch and added `gosu` for essiren in the same manner as for es5. ATTX fuseki now also has `gosu` added.
I chose `gosu` even for alpine images instead of `su-exec` for consistency, also because `gosu` was better documented.

Out of lack of inspiration the user I used in some images was `nonroot` and group `nonroot`

**Comment by joasilva** [comment]
@joasilva and @jkesanie 

The persistency of the supd versions of attx-fuseki, essiren, gm-api on an external volume is is working.

But attx-es5 doesn't stay up, and the error is this:

```ERROR: no log4j2.properties found; tried [/usr/share/elasticsearch/config] and its subdirectories```


Perhaps we should update its Dockerfile https://github.com/ATTX-project/platform-deployment/blob/feature-betterPermissions/attx-es5/Dockerfile?

For example, by changing  `COPY config ./config` to `COPY config /usr/share/elasticsearch/config` (relative paths might not work that well in the the context of our current Gradle build system).

**Comment by blankdots** [comment]
@joasilva and @jkesanie  attx-es5 the directory was like that from the original image. 
I looked up the error, however I do not think that is the issue. Nevertheless I did it as suggested.
By looking at the current log4j2.properties it seems that someone downloaded a webpage to a file, it does not look like a proper configuration file as suggested by  https://www.elastic.co/guide/en/elasticsearch/reference/5.x/settings.html 

Compare https://github.com/ATTX-project/platform-deployment/blob/7ec40ac27826226cb5bc29086b2c4f67576051c0/attx-es5/config/log4j2.properties (our previous dev environment) vs https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/log4j2.properties (from elasticsearch official). It seems the log4j2.properties was supposed to be from here: https://github.com/docker-library/elasticsearch/blob/master/5/config/log4j2.properties ?

or maybe the error it is related to this: https://github.com/elastic/ansible-elasticsearch/issues/58

-------

Test scenarios done in the attx-es5 directory:
* vanilla docker
  * build with: `docker build -t test_es5 . `
  * run: `docker run -p 9210:9210 -p 9310:9310 test_es5` (no persistence selected)
* gradle:
  * build with: `gradle buildAttxes5Image`
  * run with: `docker run -p 9210:9210 -p 9310:9310 -v /data/es5:/usr/share/elasticsearh/data attx-dev:5000/attx-es5:supd` (run with volume attached; has just one volume)

I could only detect warnings in both cases, the error could not be replicated before, nor after the changes.

**Comment by blankdots** [comment]
This is considered as done as during the https://github.com/ATTX-project/project-management/issues/82 there were no issues with the newly developed images
