### ISSUE TITLE
Deployment of ATTX components on cPouta

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/platform-deployment#28]
#### Description
Documentation and files related to deployment ATTX nodes on a OpenStack cloud.

Persistence for:
- Unified Views
- Fuseki
- ElasticSearch both of them ES5 and ESSiren
- GM-API

#### DoD
Documentation can be used to replicate deployment.
One can restart the containers without losing any data.

#### Testing
Peer Review

**Comment by blankdots** [comment]
@joasilva There is a new component that requires persistence and that is GM-API see issue https://github.com/ATTX-project/graph-component/issues/25 Unfortunately the image that has the necessary changes is waiting for review in issue https://github.com/ATTX-project/platform-deployment/issues/27 before it could be merged

**Comment by joasilva** [comment]
Started editing the provisioning procedure @https://github.com/ATTX-project/project-management/wiki/Deploying-ATTX-Components-on-Docker-Swarm. This task takes a bit longer than expected because it actually tests issues #27 and https://github.com/ATTX-project/graph-component/issues/25. Stefan has tagged the new images from #27  in attx-dev:5000 as "supd", I'll pull/tag/push them to Docker Hub tomorrow and test them in cPouta as well.

**Comment by joasilva** [comment]
Instructions updated @https://github.com/ATTX-project/project-management/wiki/Deploying-ATTX-Components-on-Docker-Swarm. Might need some improvements (suggestions welcome) and additions and checks (data persistency, etc.).

**Comment by jkesanie** [comment]
2. You could elaborate a little bit what you mean by "ATTX components". For example, what is being stored on "attx-data"? Maybe do the same for uv-data? I know services are listed in the next sections, but second bullet could contain an overview of services that will be using that volume (eg. graph store etc).

**Comment by joasilva** [comment]
@jkesanie Relevant suggestion, I'll edit the first paragraphs of the document.

**Comment by joasilva** [comment]
@jkesanie Editing done @https://github.com/ATTX-project/project-management/wiki/Deploying-ATTX-Components-on-Docker-Swarm, please review.
