### ISSUE TITLE
Implement linking related scenario of the uc1 feature

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#30]
#### Description

Scenario is included in the feature file, but is not yet implemented. 

#### DoD
No skipped tests in the report.

#### Testing
BDD

**Comment by blankdots** [comment]
Identifier based linking is executed, and the test pass. There is just one things missing or at least worth an answer, this will always pass:
```
        Given("^there are existing linking identifiers$", () -> {
            // test data is set up so, that there are linking identifiers
            assertTrue(true);

        });
```

**Comment by jkesanie** [comment]
I could have left that part out all together, because test fixtures have been set up so that there will always be linking identifiers.

**Comment by jkesanie** [comment]
On second thought, maybe this should be implemented in a better way. I'm on it.
