### ISSUE TITLE
Installation instructions (v1) on own laptop or single VM

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#31]
#### Description
Scope  of installation instructions: own PC, or single VM ("as a ATTX user, I need to install ATTX-2016 v1 release stack on my PC or single").

#### DoD
Public wiki page in the platform-deployment repo.

#### Testing
Peer-review.

**Comment by blankdots** [comment]
Should this be connected with https://github.com/ATTX-project/project-management/issues/87 ?

**Comment by joasilva** [comment]
Pasi has reviewed the instruction (https://github.com/ATTX-project/project-management/wiki/Running-the-ATTX-containerised-application-stack-in-your-own-PC-or-Mac), here are his comments:
- Docker CE is for Windows 10 only, previous versions use Docker Toolbox;
- In Windows, it's good to have VirtualBox installed before Docker CE or Toolbox;
- I want ready-made docker-compose.yml files, I don't want to install Gradle to build them;
- Please review the ready-made Docker Compose files for missing or extra space characters and add persistency for container data;
- Windows users should use Docker Quickstart Terminal, and please take into account the Docker Quickstart IP address when testing the ATTX applications (192.168.99.100);
- The ATTX stack typically is up when the message "attx_uv_dpus_1 exited with code 0" is printed on the Quickstart terminal output, please add that to the tests;
- Also add login tests to other ATTX applications such as Jena/Fuseki and ElasticSearch.

**Comment by joasilva** [comment]
Pasi's comments and suggestion updated @ https://github.com/ATTX-project/project-management/wiki/Running-the-ATTX-containerised-application-stack-in-your-own-PC-or-Mac.
