### ISSUE TITLE
Describe component interactions using some Service Discovery implementation

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#32]
#### Description
We should understand what the components and content and when to talk to each other using Service Discover component. 
How are data acquisition, processing and indexing workflows affected? 

Components to register:
- [ ] WF-API
- [ ] GM-API
- [ ] Graph Store
- [ ] Elasticsearch 1.3.4
- [ ] Elasticsearch 5.x

Come up with a set of keys and values these components register. e.g. components that are of type DC and can distribute JSON documents. 

We first need a test environment with for example 3 containers + service discovery (2 are REST APIs and one fuseki).

#### DoD
Wiki page.

#### Testing
Peer review

**Comment by joasilva** [comment]
Consul HTTP API: https://www.consul.io/api/index.html

**Comment by joasilva** [comment]
Consul cluster now up and running in attx-sandbox.hulib.helsinki.fi. You can interact with Consul's SD catalog with a web browser at@http://attx-sandbox:8500/ui/#/dc1/services, or via curl @http://attx-sandbox:8500/v1/catalog/service/web. 

The Key-Value datastore is available @http://attx-sandbox:8500/v1/kv/. For example:
```
curl -X PUT -d 'this is a test' http://attx-sandbox:8500/v1/kv/msg1
curl http://attx-sandbox:8500/v1/kv/msg1?raw
this is a test
```

**Comment by blankdots** [comment]
For the test rest API we have an image at: https://hub.docker.com/r/blankdots/test_restapi/ running the https://github.com/blankdots/pygradle-falcon-api exposing the port 4300 . It is just a simple REST API functionality without any consul capabilities. In order to register the service with consul @joasilva We need to add it on the attx-sandbox server.

**Comment by blankdots** [comment]
To be continued ... after we can reach a decision, wiki to be done.

**Comment by blankdots** [comment]
Documentation available at: https://github.com/ATTX-project/ATTX-project.github.io/blob/dev/Import/attx_project/ServiceDiscovery-Implementation.md
