### ISSUE TITLE
cPouta Cloud installation instructions

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#33]
#### Description
Instructions on how to install ATTX stack on cPouta OpenStack platform.
"as a ATTX user, I need to install scalable version of the v1 release of ATTX stack (that is available to public)".

#### DoD
Public wiki page 

#### Testing
Peer-review and peer-testing

**Comment by joasilva** [comment]
@jkesanie Actually, this task is already satisfied by https://github.com/ATTX-project/project-management/wiki/Provisioning-ATTX-Components-on-CSC-Open-Stack-(cPouta) and https://github.com/ATTX-project/project-management/wiki/Deploying-ATTX-Components-on-Docker-Swarm.
