### ISSUE TITLE
Add common java test helpers library project

### ISSUE THREAD

**Issue by joasilva** [ATTX-project/platform-deployment#35]
#### Description
Initial content should be refactored PlatformServices.
New artifact in Archiva
Add new test methods as part of the feature test refactoring.
#### DoD
new artifact dependency added to all the feature-test projects
#### Testing
Peer-review
unittesting

**Comment by blankdots** [comment]
The first version of the test-helper library is available in development-environment: https://github.com/ATTX-project/development-environment/tree/dev/dev-test-helper
A new Jenkins pipeline has been developed for this purpose and artifacts are in archiva.

The unit testing has not been performed, and probably should be left outside the scope of this issue.

**Comment by jkesanie** [comment]
TestUtils work and I have used and extended them in gc-feature-tests.

**Comment by jkesanie** [comment]
Tests would actually have to be integration tests, because most of the helper functions deal with component APIs. Since TestUtils is used to implement integration tests in other projects, we can assume that TestUtils work if the those tests work.
