### ISSUE TITLE
Get more VM resources from cPouta

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/platform-deployment#36]
#### Description
Increase disk space size in cPouta and get more vCPUs.
#### DoD
Double disk space size for cPouta VM instances and enough vCPUs for ES high availability.
#### Testing
Peer Review

**Comment by joasilva** [comment]
Request to made to CSC. The root cause was the old (and faulty) image of ElasticSearch creating lots of files in /var/lib/docker/aufs/ until the the FS became filled up.

**Comment by joasilva** [comment]
Request accepted, the project's cPouta quota has now been updated:

Cores: 8 -> 16
RAM: 33000 -> 80000
