### ISSUE TITLE
Refactor existing Integration and BDD tests in each respective environment

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/platform-deployment#37]
#### Description
Workflow component and PD and GC
#### DoD
Test are refactored and runned successfully both in jenkins and locallly, maybe fiddle around with fixtures such as queries and have them in files.
#### Testing
Peer review

**Comment by jkesanie** [comment]
gc-feature-test refactored version available in branch feature-itrefactoring

**Comment by blankdots** [comment]
@jkesanie WF tests refactored as part of https://github.com/ATTX-project/project-management/issues/88, I think this should be moved to review or Done, unless there are other changes

Also see https://github.com/ATTX-project/project-management/issues/88#issuecomment-292166563 for what has been achieved with PD and GC updated feature test in respective branches.

**Comment by jkesanie** [comment]
Added timeout exception. Can be merged now.
