### ISSUE TITLE
Services Health check endpoint

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#4]
#### Description
We need a services which monitors the status or different components, besides something related to consul.io The service will return a status of the service its endpoints and other related information.

Important also if we are going to use `dockerize` tool.

Implement for gm-api and wf-api.

#### DoD
Health check service running.
#### Testing
Unit testing

**Comment by jkesanie** [comment]
http://blog.terranillius.com/post/docker_testing/

**Comment by blankdots** [comment]
There are some libraries for python to help with the healthcheck endpoint however none focused on falcon.
Following the solution specified by http://microservices.io/patterns/observability/health-check-api.html , however without the various checks.

The functionality is simple in terms of just a `200` response from the API to indicate the application is running. More complex functionality can be implement (e.g. last healthcheck, number of endpoints etc.) however these need to be specified and feasible to implement.

**Comment by blankdots** [comment]
Updated documentation:
* https://github.com/ATTX-project/project-management/wiki/WF-API
* https://github.com/ATTX-project/project-management/wiki/Graph-Manager-API

**Comment by blankdots** [comment]
@jkesanie and/or @joasilva please review this.
To review functionality go to each api respective git repository and do `gradle build` (this will also run the tests) and start application using `./build/deployable/bin/gmapi` or `./build/deployable/bin/wfapi` and curl or use postman for the `http://localhost:4302/health` or `http://localhost:4301/health`
or 
build a jenkins pipeline for the branch `feature-healthcheck` and test the resulting artifact from archiva
For the code review see commits in this issue or the `feature-healthcheck` from each respective repository.

**Comment by jkesanie** [comment]
When running, make sure that you have logs/api.log directory and file available (create if necessary).

Both seem to be working.
