### ISSUE TITLE
Prototype Service Discovery with Consul

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/platform-deployment#41]
#### Description
Followup of https://github.com/ATTX-project/platform-deployment/issues/32

register and de-register service - when and how to do that?
discover other components - multiple types of implementations of a service registered under one name (graph store, implementation A or B)?
#### DoD
Example components registers themselves to Consul and de-register and are accessible from other services.
#### Testing
Peer review and by case BDD ?

**Comment by joasilva** [comment]
Consul HTTP API: https://www.consul.io/api/index.html

**Comment by blankdots** [comment]
Documentation available at: https://github.com/ATTX-project/ATTX-project.github.io/blob/dev/Import/attx_project/ServiceDiscovery-Implementation.md

**Comment by jkesanie** [comment]
SWARM
- serviceName = name of the container in the network

Proxy
- serviceName = name of the container in the network
- servicePath = /[service name from consul]/endpoint


Consul
- catalog
  - serviceName = application type of service
  - serviceID = service name from SWARM
  - tag = v1

- kv
  - serviceName/description = "Description of the the service"
  - serviceName/dataset =

Example
---

Elasticsearches

SWARM
- name = ES1
- name = ES5

Proxy
- serviceName = ES1
- servicePath = /ES1/jsonRestAPI/
- reqPathSearch = /ES1/jsonRestAPI/
- reqPathReplace = /

- serviceName = ES5
- servicePath = /ES5/jsonRestAPI/
- reqPathSearch = /ES5/jsonRestAPI/
- reqPathReplace = /

Consul
- catalog
  {
    serviceName: "jsonRestAPI"
    serviceID: "ES1"
    tags: ["v1"]
  }
  {
    serviceName: "jsonRestAPI"
    serviceID: "ES5"
    tags: ["v1"]
  }

- kv
  /ES1/description = "REST API that uses old version of the ES"
  /ES5/description = "REST API implemented with the current version of the ES"


Query for services of type "jsonRestAPI" and version "v1"

http://proxy/consul/catalog/service/jsonRestAPI?tag=v1

Returns:
- serviceIDs

Access the service (indexing)

PUT http://proxy/ES1/jsonRestAPI/[indexName]/[document type]

proxy/[serviceID]/[serviceName]/[endpoint]

**Comment by blankdots** [comment]
[
"docker-flow/service/jsonRestAPI_es1_v1",
"docker-flow/service/jsonRestAPI_es1_v2",
"docker-flow/service/jsonRestAPI_es2"
]

**Comment by joasilva** [comment]
@blankdots @jkesanie Simple BASH script to automate the creation of 3-node Docker Swarm based on Docker-Machine: https://raw.githubusercontent.com/ATTX-project/platform-deployment/feature-docker-machine/swarm-mode-docker-machine/createSwarm.sh

Included:
- Consul server + agents
- Flow Proxy
- Flow Swarm Listener

**Comment by blankdots** [comment]
documentation updated at: https://github.com/ATTX-project/ATTX-project.github.io/blob/dev/attx_project/ServiceDiscovery-Implementation.md
