### ISSUE TITLE
Create script for deploying demo Docker Swarm environment (docker-machine) on own PC

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/platform-deployment#42]
#### Description
We need to create a demo environment for ELAG presentation on a machine.
#### DoD
Script for deploying 3 node swarm for deploying on a laptop.
#### Testing
Manual Testing/Peer Review.

**Comment by joasilva** [comment]
Updated task, let's use plain docker-machine instead of Ansible + Vagrant.

**Comment by joasilva** [comment]
With 2048 MBs RAM docker-machines, the deployment speed is as follows:
- Time to run script and create 3 docker-machine nodes in Swarm node: 3m16s.
- Time to deploy ATTX stack in Swarm: 4m08s.

**Comment by joasilva** [comment]
Script updated here: https://github.com/ATTX-project/platform-deployment/blob/feature-docker-machine/swarm-mode-docker-machine/createSwarm.sh

**Comment by joasilva** [comment]
Some possible topics for ELAG practical demo:

1. What do you need to try out the ATTX Stack in Swarm Mode in your own PC: Viertualbox, Docker CE, Docker-Machine, the link to the SW in GitHUB (createSwarm.sh and attx-swarm.yml), link to Gitbook instructions;
2. Install the pre-requisites (links to instuctions);
3. wget createSwarm.sh  and attx-swarm.yml (practical demo);
4. Run createSwarm. (3-4 mins) and talk about something relevant (to be decided);
5. Run service deploy of attx-swarm.yml (4-5 mins) and talk about something relevant (to be decided);
6. Quick demo of UnifiedViews, ElasticSearch, etc.
7. Q&A.

**Comment by blankdots** [comment]
I think we need a new repository as a demo for ELAG2017 unless we want this to be a part of the platform-deployment repository.

**Comment by jkesanie** [comment]
ELAG2017-demo repository?

**Comment by blankdots** [comment]
done here: https://github.com/ATTX-project/elag2017-demo
