### ISSUE TITLE
Prototype Sharing Data between distributed Docker Containers

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/platform-deployment#43]
#### Description
In a situation where multiple containers are accessing the same data e.g. volume, we should be able to support in a distributed environment.
Support distributed filed shared between containers. Example technologies; NFS, Flocker, CIFS.
#### DoD
Demo.
#### Testing
Peer review

**Comment by joasilva** [comment]
Background goals and constraints to be accounted for:
- All components are containerised and they're configured in a  YML file (Docker Compose v3 foramt) and  deployable in Docker Swarm (DONE)
- We should be able to run our Docker Swarm ATTX stack in a standalone Windows/Linux PC or Mac (DONE), in VMs or bare metal servers (DONE), and in OpenStack (DONE)
- And our storage solution should support deployment in our deployment scenarios.
- There are containerised components that need highly available storage in Docker Swarm deployment for our deployment scenarios:

    MariaDB
    GM-API
    ElasticSearch 2
    ElasticSearch 5
    Fuseki

- A common shared volume for containerised components to exchange files between each other.

**Comment by joasilva** [comment]
Finally, Codento reached back on this matter, with a list of Docker volume plugins, most of them known.

Will proceed with the creation of a shared volume with Netshare Docker volume plugin (http://netshare.containx.io/) as originally planned. First in Docker Swarm in CPouta, then in Kontena.

**Comment by joasilva** [comment]
@blankdots: I propose that the frontend/backend/gm-api containers mount the shared volume as "/attx-shared".

**Comment by joasilva** [comment]
Summary of configuration changes to enable NFS file sharing between containers:
- Mount external volume to Master (attx-swarm-1) in /d/attx-shared
- Setup Master as NFS server and configure it to export the /d/attx-shared filesystem
- Install NFS client in all nodes
- Install and configure the Docker NetShare volume plugin in all hosts
- Configure the frontend/backend/gm-api services  in attx-swarm.yml to mount the exported NFS share from attx-swarm-1 as "/attx-shared".

**Comment by joasilva** [comment]
Ready for review. New attx-swarm.yml pushed to https://github.com/ATTX-project/platform-deployment/blob/dev/swarm-mode-cpouta/attx-swarm.yml.

With an NFS server and shared volume in place, and the other swarm node as NFS clients, and Docker NFS Volume plugin installed in all nodes, the changes to attx-shared.yml are as such:
Volumes:
```
  attx-shared:
    driver_opts:
      type:  nfs
      o: addr=192.168.1.31,rw
      device: ":/d/attx-shared"
```

Services:
```
volumes:
  - attx_shared:/attx-shared
```

**Comment by joasilva** [comment]
Shared volumes difinition with Kontena:
https://github.com/ATTX-project/platform-deployment/blob/feature-kontena/attx-kontena/attx-kontena.yml

Pre-requisite: create Kontena shared volume (`kontena volume create --driver local --scope stack attx-sb-share`).
