### ISSUE TITLE
Service discovery with proxy load balancer

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#44]
#### Description

Figure out how to implement server-side service discovery with Consul and Docker FlowProxy.

#### DoD
Working prototype:  
Client makes a request to a proxy and proxy is able to identify the service registered in Consul (make sure services are registered in Consul) and forward the request to the right service and endpoint. 

For example:
http://proxy/c1/hello 
- return "c1 hello"
http://proxy/c2/hello
- returns "c2 hello"

#### Testing
Peer-review, Demo

**Comment by blankdots** [comment]
@joasilva 
An example service is: https://hub.docker.com/r/blankdots/test_restapi/
Instructions:
* `docker pull blankdots/test_restapi`
* `docker run -e CONSULIP=attx-sandbox -e CONSULPORT=8500 -p 4300:4300 blankdots/test_restapi` - if you run it locally. If run on a server the CONSULIP and CONSULPORT environment variables need to be set in accordance with consult settings from the docker network or swarm or machine.

In Order to access the service:
* simple `service/health` - HTTP response should be 200;
* complex examples: https://github.com/blankdots/pygradle-falcon-api

**Comment by joasilva** [comment]
Joonas' diagram here: https://helsinkifi-my.sharepoint.com/personal/madeira_ad_helsinki_fi/_layouts/15/guestaccess.aspx?folderid=0af07ec62b04f473ebfba7dba0243d137&authkey=AUO6ZFanatsD-MVvorlFl2k

**Comment by joasilva** [comment]
Preliminary finding: Joonas' requirement is theoretically possible with Docker Flow Proxy.

If the the service registration would be done as `"curl "$PROXY_IP:8080/v1/docker-flow-proxy/reconfigure?serviceName=demo&servicePath=/demo"` (and supposing that the demo service would be just a REST "hello" IF, then it could be accessed with `curl -i $PROXY_IP/demo/hello`.

Reference from Flow Proxy's documentation (http://proxy.dockerflow.com/usage/) on "General HTTP Query Parameters":
_serviceName_	The name of the service. It must match the name of the Swarm service.

_servicePath_	The URL path of the service. Multiple values should be separated with comma (,). The parameter can be prefixed with an index thus allowing definition of multiple destinations for a single service (e.g. servicePath.1, servicePath.2, and so on). This parameter is mandatory unless serviceDomain is specified.
Example: /api/v1/books

Working on a practical demo implementation now.

**Comment by blankdots** [comment]
This is the article: https://technologyconversations.com/2016/03/21/docker-flow-proxy-on-demand-haproxy-service-discovery-and-reconfiguration/ which might help with the implementation.
@joasilva Probably my thought would be how to get that `$PROXY_IP` as and environment variable for the application running inside a container ... if possible. The alternative would be to hard-code the proxy container name and port (not that nice in a dynamic system, but an option).

I am thinking something like this is a docker-compose.yml:
```
gmapi:
  ports:
    - "4302"
  environment:
    - PROXY_IP=${PROXY_IP}
  links:
    - fuseki
```
where `$PROXY_IP` would be an environment variable for the whole docker network (again do not know if this is possible).

**Comment by joasilva** [comment]
Now I have a test docker-machine swarm running on my laptop with Consul and Flow Proxy. Here's some example workflow:

1. Request the proxy to register a "go-demo" Nginx server: with the "serviceName", "servicePath", and "port" parameters:
`curl "$(docker-machine ip swarm-1):8080/v1/docker-flow-proxy/reconfigure?serviceName=go-demo&servicePath=/demo&port=8080&distribute=true"`

`{"Mode":"swarm","Status":"OK","Message":"Distributed to all instances","ServiceName":"go-demo","AclName":"","AddReqHeader":null,"AddResHeader":null,"CheckResolvers":false,"ConnectionMode":"","ConsulTemplateBePath":"","ConsulTemplateFePath":"","DelReqHeader":null,"DelResHeader":null,"Distribute":true,"HttpsOnly":false,"HttpsPort":0,"IsDefaultBackend":false,"OutboundHostname":"","PathType":"","RedirectWhenHttpProto":false,"ReqRepReplace":"","ReqRepSearch":"","ReqPathReplace":"","ReqPathSearch":"","ServiceCert":"","ServiceDomain":null,"ServiceDomainMatchAll":false,"SetReqHeader":null,"SetResHeader":null,"SslVerifyNone":false,"TemplateBePath":"","TemplateFePath":"","TimeoutServer":"","TimeoutTunnel":"","Users":null,"XForwardedProto":false,"ServiceColor":"","ServicePort":"","AclCondition":"","FullServiceName":"","Host":"","LookupRetry":0,"LookupRetryInterval":0,"ServiceDest":[{"Port":"8080","ReqMode":"http","ReqModeFormatted":"","ServicePath":["/demo"],"SrcPort":0,"SrcPortAcl":"","SrcPortAclName":"","VerifyClientSsl":false,"UserAgent":{"Value":null,"AclName":""}}]}`

2. Check that the newly registered service can be accessed trough the Proxy:
`curl -i $(docker-machine ip swarm-1)/demo/hello`

```HTTP/1.1 200 OK
Date: Fri, 19 May 2017 07:49:57 GMT
Content-Length: 14
Content-Type: text/plain; charset=utf-8

hello, world!```

**Comment by blankdots** [comment]
For the simple pygradle demo container: `docker pull blankdots/test_restapi:plain`

**Comment by joasilva** [comment]
We deployed the pygradle test container like this:
`docker service create --name pygradle --network proxy --network attx -p 4300:4300 blankdots/test_restapi:plain`

And then, we registered its "health" and "index" service paths as follows:
`curl "$(docker-machine ip swarm-1):8080/v1/docker-flow-proxy/reconfigure?serviceName=pygradle&servicePath=/health,/0.1/index&port=4300&distribute=true"`

And we accessed them the following way:
```
$ curl -i -X POST $(docker-machine ip swarm-1)/0.1/index

HTTP/1.1 400 Bad Request
Server: gunicorn/19.6.0
Date: Fri, 19 May 2017 10:24:22 GMT
content-type: application/json; charset=UTF-8
content-length: 104
vary: Accept

{
    "title": "Invalid data",
    "description": "Could not properly parse the provided data as JSON"
}
```
```
curl -i $(docker-machine ip swarm-1)/health

HTTP/1.1 200 OK
Server: gunicorn/19.6.0
Date: Fri, 19 May 2017 10:36:19 GMT
content-length: 0
content-type: application/json; charset=UTF-8

```

**Comment by joasilva** [comment]
Starting up the listening service:
`$ docker service create --name swarm-listener     --network proxy     --mount "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock"     -e DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure     -e DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove     --constraint 'node.role==manager'     vfarcic/docker-flow-swarm-listener
 2588* docker service create --name proxy     -p 80:80     -p 443:443     --network proxy     -e MODE=swarm  -e replicas=3   -e LISTENER_ADDRESS=swarm-listener     vfarcic/docker-flow-proxy`


Update: with Swarm Listener it's possible to auto-register services into Docker Flow.

`$ docker service create --name pygradle --network proxy --network attx --label com.df.notify=true --label com.df.distribute=true --label com.df.servicePath=/health  --label com.df.port=4300 blankdots/test_restapi:plain`


`$ curl -i $(docker-machine ip swarm-1)/health`
```
HTTP/1.1 200 OK
Server: gunicorn/19.6.0
Date: Fri, 19 May 2017 13:09:43 GMT
content-length: 0
content-type: application/json; charset=UTF-8
```

**Comment by joasilva** [comment]
This works as such:
```
$ docker service create --name pygradle --network proxy --label com.df.notify=true --label com.df.distribute=true --label com.df.servicePath=/p/health --label com.df.port=4300 blankdots/test_restapi:plain

$ curl -i $(docker-machine ip swarm-1)/p/health
HTTP/1.1 404 Not Found
Server: gunicorn/19.6.0
Date: Mon, 22 May 2017 08:09:59 GMT
content-length: 0
content-type: application/json; charset=UTF-8
```

The "/p/health" server can be found but not the application (no /p/health at the the server, hence "404")

**Comment by joasilva** [comment]
Now it works:
```
curl -i $(docker-machine ip swarm-1)/phealth/
HTTP/1.1 200 OK
Server: gunicorn/19.6.0
Date: Mon, 22 May 2017 10:00:59 GMT
content-length: 0
content-type: application/json; charset=UTF-8
```

The launch command parameters were:
```
docker service create --name pygradle -p 4300:4300 --network proxy --label com.df.notify=true --label com.df.distribute=true --label com.df.servicePath=/phealth --label com.df.port=4300 --label com.df.reqPathSearch='/phealth' --label com.df.reqPathReplace='/health' blankdots/test_restapi:plain
```

**Comment by blankdots** [comment]
@joasilva I am curios if this configuration is for swarm services ?
We might be missing the `outboundHostname` parameter, if it is not a swarm service, and then maybe we can do without the need for replace of a path see http://proxy.dockerflow.com/non-swarm/#manually-configuring-non-swarm-services  or http://proxy.dockerflow.com/non-swarm/#configuring-non-swarm-services-through-environment-variables ... can we try it.

Also we need to try to register multiple paths, as one service has multiple paths.

**Comment by joasilva** [comment]
And trying out now with a new container exposing "health" as well:
```
$ docker service create --name mutteri -p 49001:4300 --network proxy --label com.df.notify=true --label com.df.distribute=true --label com.df.servicePath=/m/health --label com.df.port=4300 --label com.df.reqPathSearch='/m/health' --label com.df.reqPathReplace='/health' blankdots/test_restapi:plain

$ curl -i $(docker-machine ip swarm-1)/m/health
HTTP/1.1 200 OK
Server: gunicorn/19.6.0
Date: Mon, 22 May 2017 11:13:04 GMT
content-length: 0
content-type: application/json; charset=UTF-8
```

**Comment by joasilva** [comment]
That's for swarm: all our containerised services should run in the ATTX swarm. "outboundHostname" is used to find services (containers) running outside the ATTX swarm, hence not needed (all swarm services can find each other if they're on the same overlay network).

________________________________

**Comment by joasilva** [comment]
And for the new feature creep (multiple endpoints in one exposed service):

```
$ docker service create --name mutteri -p 49001:4300 --network proxy --label com.df.port=4300 --label com.df.notify=true --label com.df.distribute=true --label com.df.servicePath=/m/health,/m/index --label com.df.reqPathSearch='/m/health' --label com.df.reqPathReplace='/health' --label com.df.reqPathSearch='/m/index' --label com.df.reqPathReplace='/0.1/index' blankdots/test_restapi:plain

$ curl -i $(docker-machine ip swarm-1)/m/index
HTTP/1.1 405 Method Not Allowed
Server: gunicorn/19.6.0
Date: Mon, 22 May 2017 12:19:56 GMT
content-length: 0
content-type: application/json; charset=UTF-8
allow: POST, OPTIONS


$ curl -i $(docker-machine ip swarm-1)/m/health
HTTP/1.1 404 Not Found
Server: gunicorn/19.6.0
Date: Mon, 22 May 2017 13:42:17 GMT
content-length: 0
content-type: application/json; charset=UTF-8

```

**Comment by joasilva** [comment]
And here's the last fine-tuning from Joonas:

```
docker service create --name pygradle \
-p 4300:4300 --network proxy \
--label com.df.port=4300 \
--label com.df.notify=true \
--label com.df.distribute=true \
--label com.df.servicePath=/p/health,/p/0.1/index \
--label com.df.reqPathSearch='/p/' \
--label com.df.reqPathReplace='/' \
blankdots/test_restapi:plain

curl -i $(docker-machine ip swarm-3)/p/health
HTTP/1.1 200 OK
Server: gunicorn/19.6.0
Date: Mon, 22 May 2017 14:19:53 GMT
content-length: 0
content-type: application/json; charset=UTF-8


curl -i $(docker-machine ip swarm-3)/p/0.1/index
HTTP/1.1 405 Method Not Allowed
Server: gunicorn/19.6.0
Date: Mon, 22 May 2017 14:20:06 GMT
content-length: 0
content-type: application/json; charset=UTF-8
allow: POST, OPTIONS
```

**Comment by blankdots** [comment]
docker service create --name pygradle \
-p 4300:4300 --network proxy \
--label com.df.port=4300 \
--label com.df.notify=true \
--label com.df.distribute=true \
--label com.df.servicePath=/p/health,/p/0.1/index \
--label com.df.reqPathSearch='/p/' \
--label com.df.reqPathReplace='/' \
blankdots/test_restapi:plain

**Comment by joasilva** [comment]
@jkesanie and @blankdots.
Wiki updated, please review: https://github.com/ATTX-project/ATTX-project.github.io/blob/dev/attx_project/Consul-for-Service-Discovery-on-Docker-Swarm.md
