### ISSUE TITLE
Create a tagged UnifiedViews image in Docker hub

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/platform-deployment#46]
#### Description
we need our own tagged image of UnifiedViews to have more control on the changes.
#### DoD
UnifiedViews Image available in Docker Hub.
#### Testing
Peer Review

**Comment by joasilva** [comment]
Images tagged as:
attxproject/unified-views-mariadb:1.1
attxproject/unified-views-shared:1.1
attxproject/unified-views-frontend:1.1
attxproject/unified-views-backend:1.1

**Comment by blankdots** [comment]
Review: Tested the elag2017 demo with the images, the DPUs and pipelines are not uploaded for some reason (looking into it).

**Comment by blankdots** [comment]
@joasilva and @jkesanie (not part of this issue) however there are multiple images with the same function on https://hub.docker.com/u/attxproject/dashboard/ (e.g. 3 UnifedViews share, 2 unifiedViews backend etc. ) it might be better to have them as tags rather than separate images, it becomes confusing which ones a USER might want to use and in which combination.

**Comment by blankdots** [comment]
as part of this issue there needs to be a new DPU image created also a new fuseki image created, the tags have been prepared however the artifacts cannot be built due to UnifiedViews repository issues and partly Archiva repository issues.

**Comment by blankdots** [comment]
New images have been generated and feature tests pipelines have been successfully executed.

**Comment by jkesanie** [comment]
This needs to be done again, because there are new UV images available.

**Comment by blankdots** [comment]
New images available:
- attxtest/uv-attx-dpus:1.2
- attxtest/uv-attx-dpus:elag2017 for https://github.com/ATTX-project/elag2017-demo
- attxtest/unified-views-mariadb:stable-1.2
- attxtest/unified-views-shared:stable-1.2
- attxtest/unified-views-backend:stable-1.2
- attxtest/unified-views-frontend:stable-1.2

Images tested with https://github.com/ATTX-project/elag2017-demo and appear to be working again
