### ISSUE TITLE
Experiment with Docker storage drivers

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#48]
#### Description
_Describe the issue or task at hand with dependencies and possible links to code/external/internal sources._
#### DoD
_Itemized things or artifacts of the task at hand, what one expects to achieve - tangible output._
#### Testing
_How one would test that the things/artifacts have been achieved. Options (Peer review, Unit Test, BDD testing, Integration Test)._

**Comment by joasilva** [comment]
Reminder:
- REXRAY for S3 (rexray/s3fs): https://libstorage.readthedocs.io/en/stable/user-guide/storage-providers/#aws-s3fs
