### ISSUE TITLE
Implement shared filesystem with docker swarm (OpenStack)

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#57]
#### Description

Implementation (configurations + docs) for Docker Swarm running in OpenStack cloud.
Maybe restructure the configuration files?

#### DoD

configurations + docs

#### Testing
Peer-review

**Comment by jkesanie** [comment]
Check documentation and warm up cPouta instances

**Comment by joasilva** [comment]
Continuing the work from https://github.com/ATTX-project/platform-deployment/issues/43. Documentation needed @https://attx-project.github.io.

**Comment by joasilva** [comment]
Ready for review: https://github.com/ATTX-project/ATTX-project.github.io/blob/dev/attx_project/Shared-NFS-Swarm-Cloud.md
