### ISSUE TITLE
Add overrides to ATTX Platform docker-compose

### ISSUE THREAD

**Issue by joasilva** [ATTX-project/platform-deployment#6]
#### Description
The current docker-compose.yml for the ATTX Platform (https://github.com/ATTX-project/platform-deployment/blob/dev/docker-compose.yml) doesn't take into account the specificities of different docker engine environments (attx-sandbox, MacOS, etc.).

It would be nice to have the option to startup the docker-compose ATTX Platform with override options for demo and sandbox. For example, using a volume container for the UV DB (demo), and /data filesystem persistency (sandbox).

#### DoD

Docker override files with appropriate configurations for "demo" and "sandbox" 

#### Testing

Manual testing / peer review

**Comment by blankdots** [comment]
Test initialisation: remove all exited Docker containers `(docker rm ($docker ps -a -q))` before running docker-compose.
