### ISSUE TITLE
Add dev tagged images to the DockerHub

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#64]
#### Description
Implemented by modifying the existing Jenkins pipelines (+gradle files).

#### DoD

dev tagged images in the hub

#### Testing
peer-review

**Comment by joasilva** [comment]
Done so far:
- attx-activemq-image
- attx-es5-image
- attx-fuseki
- provenance-service-image
- service-uv-provenance-image

**Comment by blankdots** [comment]
@joasilva 3 more to go:
* graphmanager-service-image
* servive-rml-service-image
* uv-attx-dpus-image

**Comment by joasilva** [comment]
The following are done:
- graphmanager-service-image
- servive-rml-service-image
- uv-attx-dpus-image
