### ISSUE TITLE
ATTX Kontena YML Stack for JYU use case

### ISSUE THREAD

**Issue by joasilva** [ATTX-project/platform-deployment#66]
#### Description
Now that we have a demo environment for JYU in Kontena Cloud, we should also have a customised Kontena YML defining the services that should be exposed there.

#### DoD
Kontena Stack YML with appropriate LB configuration, eventually DNS service.

#### Testing
Manual testing, peer review.

**Comment by blankdots** [comment]
Done here: https://github.com/ATTX-project/platform-deployment/blob/master/attx-stack-kontena/attx-jyu-kontena.yml
