### ISSUE TITLE
Deploy ATTX platform stack using Ansible playbook on sandbox

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/platform-deployment#7]
#### Description
Deploy ATTX platform stack using Ansible playbook on sandbox.
#### DoD
ATTX platform stack: UnifiedViews + Fuseki + WF-API + elasticsearch running on the VM host configured in https://github.com/ATTX-project/project-management/issues/45
#### Testing
Peer review

**Comment by joasilva** [comment]
Ansible playbook available @https://github.com/ATTX-project/platform-deployment/blob/feature-ansible-deployment/single_host_deployment.yml 

Successfully tested in Centos7 VM attx-test-17 (RHEL7.3), and attx-sandbox (RHEL7.3).
