### ISSUE TITLE
Add basic configuration for Fuseki

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#9]
#### Description
Currently the image starts up a completely empty Fuseki instance. We need at least one dataset (/ds). 
Admin User should be set up.

#### DoD
Started up Fuseki has datasets, there needs to be at least 1 dataset.
#### Testing
Peer review

**Comment by blankdots** [comment]
https://jena.apache.org/documentation/fuseki2/fuseki-configuration.html
